### ISSUE TITLE
Fix transition & back button issues

### ISSUE THREAD

**Issue by DanTup** [DanTup/tab_route_test#1]

**Comment by DanTup** [comment]
@chunhtai here's a small repro of the routing issue I'm trying to solve.

On the [master branch](https://github.com/DanTup/tab_route_test/blob/master/lib/main.dart) I'm using `Navigator.pushNamed` to update the address bar. This persists the tab name in the URL, but results in full page transitions.

On the [pushstate branch](https://github.com/DanTup/tab_route_test/blob/pushstate/lib/main.dart) I [changed it](https://github.com/DanTup/tab_route_test/commit/63a2afd8e091322573306508e520c9e049b7becc) to use HTML's pushState. This updates the address bar correctly, and keeps the slide animation between tabs, however the back button behaves erratically, sometimes reloading the same tab or getting out of sync with the address bar. I tried various combinations of pushState and `addLocalHistoryEntry` but they all seem to have issues with the back button.

On the [new-router branch](https://github.com/DanTup/tab_route_test/blob/new-router/lib/main.dart) I [started trying to use](https://github.com/DanTup/tab_route_test/commit/d875c5f7815ed7b127dd8d2e7a692be6ef02a7d1) your new branch and the Stocks example to try and use the new `RouterDelegate`, though I haven't managed to make it work (in part because I don't think I completely understand all the parts required).

Any pointers appreciated!

**Comment by chunhtai** [comment]
will take a look

**Comment by chunhtai** [comment]
@DanTup 
I modified the example a bit, and it should work with the latest code in my router branch (I have to made some change to fix null safety feature) https://github.com/flutter/flutter/pull/55316/files

https://gist.github.com/chunhtai/113ea72e92746371c6fd105cdceb707f

It turns out the example you are trying to make does not really need a navigator because you don't want the page transition. So I modify the router delegate to build the scafford directly.

**Comment by DanTup** [comment]
@chunhtai thanks!

I tried this out with your latest code, but the page initially loads blank because of:

```
if (routes.isEmpty) return Container();
```

I changed this to:

```
return MyTabbedPage(
      initialTab: routes.isEmpty ? 'left' : routes.last,
    );
```

Which gets the page rendering, and mostly works correctly - however if I hit refresh, it goes back to the left page. I think the hard-coded `'left'` here needs to instead be able to default to what's in the current route in the address bar when pressing refresh, but it's not clear to me how best to achieve this.

> It turns out the example you are trying to make does not really need a navigator because you don't want the page transition.

That's true for this example, but in the real app (DevTools) it's a bit more complicated (there are some other additional routes) so it might not be possible to remove. If that might affect how this works, let me know and I'll do some digging to see if it's really needed there.

Thanks!

**Comment by chunhtai** [comment]
@DanTup I didn't have the issues you mentioned when running the example, do you see any error message in the console?
`if (routes.isEmpty) return Container();` is a place holder until the route name is parsed, this should rebuild with something in the routes after it is done.

`however if I hit refresh, it goes back to the left page.` This is also not expected, did you see the url changes when you navigate to different tab?

**Comment by DanTup** [comment]
I get a warning in the dev console, but I don't think it's affecting anything. Here's what I see when I run:

<img width="1202" alt="Screenshot 2020-05-14 at 14 28 20" src="https://user-images.githubusercontent.com/1078012/81940173-3826a300-95ef-11ea-83c8-bea9c6778adc.png">

It's definitely rendering something, as the debug banner appears (this is why I suspect it's just returning the `Container()`).

I'm running with the latest version of Flutter from chunhtai/nav-refactor-router (dbba6777e9) and the code from the [new-route](https://github.com/DanTup/tab_route_test/tree/new-router) branch here, which is copied from your gist. I was running from VS Code, though `flutter run -d chrome` from the terminal renders the same.

> This is also not expected, did you see the url changes when you navigate to different tab?

Yep, I did. Though I suspect this issue is probably related to the other one. If I can fix the first, maybe that will solve this too.

**Comment by DanTup** [comment]
I added some debug logging (a9298fa97090039bd5bad8487c9e746ee28dc4ae) and this is the output and it logs:

![Screenshot 2020-05-14 at 14 39 18](https://user-images.githubusercontent.com/1078012/81941421-b6377980-95f0-11ea-9585-9fcdc4fc4ce9.png)

So it seems that `setNewRoutePath` is being called, but it never rebuilds. If I insert `notifyListeners();` into `setNewRoutePath` that seems to solve that - the page now loads correctly. Is this a correct fix?

That also seems to fix the other issue with refreshing! :) However I see another issue now:

- Load the page
- Click Right
- Click Left
- Click Back (this correctly goes to Right)
- Click Back (this correctly goes to Left, however "left" is gone from the address bar)
- Click Back again (the URL fragment is removed entirely)

Now, clicking between tabs is no longer updating the address bar, but I'm not sure why. This breaks refreshing again.

(its possible this is caused by me inserting `notifyListeners()` if it's not supposed to be there though!)

**Comment by chunhtai** [comment]
Are you sure you have the latest code from my router branch? I think there is something weird about the null safety and i have to make a small change in the router code to make it work.

**Comment by DanTup** [comment]
> Are you sure you have the latest code from my router branch?

Yeah - that was my first thought, so I checked again - the hash I posted above was copied from the output of `flutter --version` (after I changed to your branch and deleted flutter_tools.snapshot just to be sure), which I also compared manually to your GitHub repo.

I presume there aren't changes to the engine or anything I need, and that the artifacts/SDK downloaded when I run `flutter` after switching to your branch includes everything necessary?

So is the `notifyListeners` call that I added *not* necessary?

**Comment by chunhtai** [comment]
I found a bug in the router code, I fixed it and push to the branch, the code should work now

**Comment by DanTup** [comment]
@chunhtai great, that works!

Though the issue described above still exists though - if you press `back` too many times so that the `#/` is removed, then clicking tabs no longer updates the address bar.

Is it expected that both `/` and `/#/` are in the history? I think if `/#/` had replaced `/` such that you couldn't "go back" to just `/` that would prevent this from happening?

**Comment by DanTup** [comment]
@chunhtai I presume https://github.com/flutter/flutter/pull/58511 replaces the original PR? Can some of this code be removed now? (your comment suggests making some cases simpler - is this one of them?). Thanks!

**Comment by chunhtai** [comment]
The PR https://github.com/flutter/flutter/pull/58511 is only a portion of the original PR. I decided to separate the original pr out to several smaller PRs.

Back to your question, which code are you referring to?

**Comment by DanTup** [comment]
> is only a portion of the original PR

Ah, ok - are there other PRs open I can watch for when this is all landed? (I'm wondering when I can try to update my sample to work on the main Flutter master code, so I could then try to implement in DevTools).

> Back to your question, which code are you referring to?

Nothing specific - but in that PR you said "This PR introduce several page classes for common use cases" so I wondered whether any of those simplified this example (for example whether there were implemenations of [some of these classes](https://github.com/DanTup/tab_route_test/blob/a9298fa97090039bd5bad8487c9e746ee28dc4ae/lib/main.dart#L117L187) that might have simplified them any).

**Comment by chunhtai** [comment]
This is the other PR https://github.com/flutter/flutter/pull/60299, and it is mainly focusing on the router widget.
The API changed a little bit from the original one because we would like to make use of state restoration. Otherwise, it is pretty much the same.

**Comment by chunhtai** [comment]
The pr https://github.com/flutter/flutter/pull/58511 is focusing on simplifying the [Page](https://api.flutter.dev/flutter/widgets/Page-class.html) class, I don't think it can be applied in this example because it does not use navigator and pages.

**Comment by DanTup** [comment]
@chunhtai I tried updating this sample for the latest code on Flutter's master branch (5cbb813) but the URL in the address bar doesn't seem to update at all now. Is there anything additional I need to add?
